language: php
php:
    - 5.5
    - 5.6
    - 7
    - hhvm
matrix:
    allow_failures:
        -
            php: hhvm
cache:
    directories:
        - $HOME/.composer/cache
before_install:
    - 'composer self-update'
    - 'composer --version'
    - './vendor/bin/hidev --version'
    - './vendor/bin/hidev travis/install'
sudo: false
install:
    - './vendor/bin/hidev travis/install'
script:
    - './vendor/bin/hidev travis/script'
after_script:
    - './vendor/bin/hidev travis/after_script'
