package:
    name:           hidev-travis-ci
    namespace:      hidev\travisci
    headline:       HiDev Travis CI
    title:          Travis CI plugin for HiDev
    type:           yii2-extension
    keywords:       travis, hidev, plugin, continuous integration
    year:           2015
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.

        This plugin enables [Travis CI](https://travis-ci.org/) support for HiDev.

require:
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-readme:        "*@dev"
    hiqdev/hidev-vendor:        "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-composer:      "*@dev"
    hiqdev/hidev-travis-ci:     "*@dev"
    hiqdev/hidev-scrutinizer:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"
